spring:
  # datasource
  datasource:
    url: jdbc:mysql://120.55.193.51:3306/sxrule_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: food@INSPECT@20151103
  application:
    name: rule
  # JPA 相关配置
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    database: 0
server:
  # 服务器的HTTP端口，默认为80
  port: 8088